spring:
  datasource:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false

jwt:
  secret: mySecretKeyForJWTInProductionUseEnvironmentVariable
  expiration: 86400000

logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG