spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/myproject_db
spring.datasource.username=postgres
spring.datasource.password=antoni0paper0
spring.datasource.driver-class-name=org.postgresql.Driver
