server:
  port: 8081

spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/myproject_db
    username: postgres
    password: antoni0paper0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJwtTokenGenerationMustBeAtLeast256BitsLongAndSecure}
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: english-learning-platform
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always