server:
  port: 8081

spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/myproject_db
    username: postgres
    password: antoni0paper0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false

jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJwtTokenGenerationMustBeAtLeast256BitsLongAndSecure}
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    liquibase: INFO